backend:
  name: github
  repo: sercancicek/gatsby-netlify-cms

media_folder: static/assets
public_folder: assets

collections:
  - name: blog
    label: Blog
    folder: src/posts
    create: true
    fields:
      - { name: title, label: Title }
      - { name: slug, label: Slug }
      - { name: date, label: Date, widget: date }
      - { name: body, label: Body, widget: markdown }