backend:
  name: github
  repo: sercancicek/gatsby-netlify-cms

media_folder: static/assets
public_folder: assets

collections:
  - name: blog
    label: Blog
    folder: src/posts
    slug: '{{slug}}'
    create: true
    fields:
      - { name: title, label: Title }
      - { name: slug, label: Slug }
      - { name: date, label: Date, widget: date }
      - { name: body, label: Body, widget: markdown }
  - label: "Pages"
    name: "pages"
    files:
      - label: "Home Page"
        name: "home"
        file: "src/homeMD/index.md"
        fields:
          - {label: Title, name: h1, widget: string}
          - {label: Sub Title, name: h2, widget: string}
          - {label: Paragraph, name: p, widget: string}